version: "3.0"

services:
  reverse-proxy:
    image: traefik:v2.1.3
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker=true
      - --certificatesResolvers.le.acme.httpChallenge.entryPoint=web
      - --certificatesresolvers.le.acme.email=scs-it@unisg.ch
      - --certificatesresolvers.le.acme.storage=/acme.json
      - --providers.docker.exposedByDefault=false
      - --serversTransport.insecureSkipVerify=true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/letsencrypt/acme.json:/acme.json
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
  

  app:
    image: openjdk
    command: "java -jar /data/app-0.1.0.jar"
    restart: unless-stopped
    volumes:
      - ./:/data/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`app.${PUB_IP}.se.scs.unisg.ch`)"
      - "traefik.http.routers.app.service=app"
      - "traefik.http.services.app.loadbalancer.server.port=8080"
      - "traefik.http.routers.app.tls=true"
      - "traefik.http.routers.app.entryPoints=web,websecure"
      - "traefik.http.routers.app.tls.certresolver=le"

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --ssl=0
    restart: always
    environment:
      MYSQL_DATABASE: teaching
      MYSQL_ROOT_PASSWORD: pkjFx3sgoKuxe_Jck9Nu
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
        #labels:
        #- "traefik.enable=true"
        #- "traefik.tcp.routers.db.rule=HostSNI(`*`)"
        #- "traefik.tcp.routers.db.entryPoints=db"
        #- "traefik.tcp.routers.adminer.tls=true"
        #- "traefik.tcp.routers.adminer.tls.certresolver=le"

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    ports:
      - 8080:8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=Host(`dbadmin.${PUB_IP}.se.scs.unisg.ch`)"
      - "traefik.http.routers.adminer.tls=true"
      - "traefik.http.routers.adminer.entryPoints=web,websecure"
      - "traefik.http.routers.adminer.tls.certresolver=le"
      
